spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sisaws
    username: sisaws
    password: sisaws123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
