spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sisaws}
    username: ${DB_USERNAME:sisaws}
    password: ${DB_PASSWORD:sisaws123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false
